In [1]:
from brian2 import *
from brian2tools import *

In [2]:
# Create voltage traces for an activation experiment
input_traces = zeros((10,5))*volt
for i in range(5):
    input_traces[5:,i]=i*10*mV

In [5]:
np.shape(input_traces)

(10, 5)

In [6]:
input_traces

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0., 10., 20., 30., 40.],
       [ 0., 10., 20., 30., 40.],
       [ 0., 10., 20., 30., 40.],
       [ 0., 10., 20., 30., 40.],
       [ 0., 10., 20., 30., 40.]]) * mvolt

In [7]:
output_traces

array([[  0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.],
       [  0., 100., 200., 300., 400.],
       [  0., 100., 200., 300., 400.],
       [  0., 100., 200., 300., 400.],
       [  0., 100., 200., 300., 400.],
       [  0., 100., 200., 300., 400.]]) * pamp

In [3]:
# Create target current traces
output_traces = 10*nS*input_traces

In [4]:
model = Equations('''
I = g*(v-E) : amp 
g : siemens (constant)
E : volt (constant)
''')
params, fits, error = fit_traces(model = model, input_var = 'v', output_var = 'I',\
    input = input_traces, output = output_traces,
    dt = 0.1*ms, g = [1*nS, 30*nS], E = [-20*mV,100*mV],
    tol = 1e-6)

INFO       No numerical integration method specified, using method 'linear' (took 0.01s). [brian2.stateupdaters.base.method_choice]


NeuronGroup(clock=Clock(dt=100. * usecond, name='defaultclock'), when=start, order=0, name='neurongroup')


WARNING    /home/alteska/anaconda3/envs/brian_opt/lib/python3.6/site-packages/Cython-0.29.7-py3.6-linux-x86_64.egg/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/alteska/.cython/brian_extensions/_cython_magic_44454a1cdf60ca24d0958b9b1eda61f5.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
 [py.warnings]


[[ -2.84445005  -2.84445005  -2.84445005  -2.84445005  -2.84445005]
 [ -2.84445005  -2.84445005  -2.84445005  -2.84445005  -2.84445005]
 [ -2.84445005  -2.84445005  -2.84445005  -2.84445005  -2.84445005]
 [ -2.84445005  -2.84445005  -2.84445005  -2.84445005  -2.84445005]
 [ -2.84445005  -2.84445005  -2.84445005  -2.84445005  -2.84445005]
 [ -2.84445005  99.14947847 201.14340699 303.1373355  405.13126402]
 [ -2.84445005  99.14947847 201.14340699 303.1373355  405.13126402]
 [ -2.84445005  99.14947847 201.14340699 303.1373355  405.13126402]
 [ -2.84445005  99.14947847 201.14340699 303.1373355  405.13126402]
 [ -2.84445005  99.14947847 201.14340699 303.1373355  405.13126402]] pA


In [8]:
params

{'g': 1.0199392851649418e-08, 'E': 0.00027888425199389805}

In [12]:
fits

array([[ -2.84445005,  -2.84445005,  -2.84445005,  -2.84445005,
         -2.84445005],
       [ -2.84445005,  -2.84445005,  -2.84445005,  -2.84445005,
         -2.84445005],
       [ -2.84445005,  -2.84445005,  -2.84445005,  -2.84445005,
         -2.84445005],
       [ -2.84445005,  -2.84445005,  -2.84445005,  -2.84445005,
         -2.84445005],
       [ -2.84445005,  -2.84445005,  -2.84445005,  -2.84445005,
         -2.84445005],
       [ -2.84445005,  99.14947847, 201.14340699, 303.1373355 ,
        405.13126402],
       [ -2.84445005,  99.14947847, 201.14340699, 303.1373355 ,
        405.13126402],
       [ -2.84445005,  99.14947847, 201.14340699, 303.1373355 ,
        405.13126402],
       [ -2.84445005,  99.14947847, 201.14340699, 303.1373355 ,
        405.13126402],
       [ -2.84445005,  99.14947847, 201.14340699, 303.1373355 ,
        405.13126402]]) * pamp