In [1]:
from brian2 import *
from brian2tools import *
from nevergrad.optimization import optimizerlib
from nevergrad import instrumentation as inst

In [5]:
import numpy as np

In [1]:
candidates, parameters = [], []

In [1]:
# create input and output
input_traces = zeros((10,5))*volt
for i in range(5):
    input_traces[5:,i]=i*10*mV

In [4]:
input_traces

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0., 10., 20., 30., 40.],
       [ 0., 10., 20., 30., 40.],
       [ 0., 10., 20., 30., 40.],
       [ 0., 10., 20., 30., 40.],
       [ 0., 10., 20., 30., 40.]]) * mvolt

In [6]:
np.shape(input_traces)

(10, 5)

In [55]:
Ntraces, Nsteps = input_traces.shape
Nsteps, Ntraces = input_traces.shape

print(Ntraces)
print(Nsteps)

5
10


In [3]:
parameters = [[-2.987692940137817, 2.7665693309883475], [1.7656649670497688, 4.355164988553166], [-3.396113359969762, 5.8764146494521565], [3.476272213050588, 2.69614839679754], [-0.8150020137777353, 5.370702058933406], [-0.31505362817895305, 6.5020175096488675], [-0.7537218014781458, 1.2574828125672015], [-2.620295450337791, 8.10011637748659], [-1.3548138729548458, 6.305132249939209], [-2.285301665576897, 1.9248265371193507]]
parameters

[[-2.987692940137817, 2.7665693309883475],
 [1.7656649670497688, 4.355164988553166],
 [-3.396113359969762, 5.8764146494521565],
 [3.476272213050588, 2.69614839679754],
 [-0.8150020137777353, 5.370702058933406],
 [-0.31505362817895305, 6.5020175096488675],
 [-0.7537218014781458, 1.2574828125672015],
 [-2.620295450337791, 8.10011637748659],
 [-1.3548138729548458, 6.305132249939209],
 [-2.285301665576897, 1.9248265371193507]]

In [11]:
parameter_names = ['g', 'E']

In [13]:
popsize, _ = shape(parameters)
N = popsize * len(parameter_names)
N

20

In [14]:
Ntraces

10

In [18]:
d = dict()
parameters = array(parameters)
parameters

array([[-2.98769294,  2.76656933],
       [ 1.76566497,  4.35516499],
       [-3.39611336,  5.87641465],
       [ 3.47627221,  2.6961484 ],
       [-0.81500201,  5.37070206],
       [-0.31505363,  6.50201751],
       [-0.7537218 ,  1.25748281],
       [-2.62029545,  8.10011638],
       [-1.35481387,  6.30513225],
       [-2.28530167,  1.92482654]])

In [42]:
(ones((N, Ntraces)) * parameters.T[0]).flatten()

array([-2.98769294,  1.76566497, -3.39611336,  3.47627221, -0.81500201,
       -0.31505363, -0.7537218 , -2.62029545, -1.35481387, -2.28530167,
       -2.98769294,  1.76566497, -3.39611336,  3.47627221, -0.81500201,
       -0.31505363, -0.7537218 , -2.62029545, -1.35481387, -2.28530167,
       -2.98769294,  1.76566497, -3.39611336,  3.47627221, -0.81500201,
       -0.31505363, -0.7537218 , -2.62029545, -1.35481387, -2.28530167,
       -2.98769294,  1.76566497, -3.39611336,  3.47627221, -0.81500201,
       -0.31505363, -0.7537218 , -2.62029545, -1.35481387, -2.28530167,
       -2.98769294,  1.76566497, -3.39611336,  3.47627221, -0.81500201,
       -0.31505363, -0.7537218 , -2.62029545, -1.35481387, -2.28530167,
       -2.98769294,  1.76566497, -3.39611336,  3.47627221, -0.81500201,
       -0.31505363, -0.7537218 , -2.62029545, -1.35481387, -2.28530167,
       -2.98769294,  1.76566497, -3.39611336,  3.47627221, -0.81500201,
       -0.31505363, -0.7537218 , -2.62029545, -1.35481387, -2.28

In [28]:
for name, value in zip(parameter_names, parameters.T):
    print(name, value)
    d[name] = (value * ones((N,Ntraces))).flatten()

g [-2.98769294  1.76566497 -3.39611336  3.47627221 -0.81500201 -0.31505363
 -0.7537218  -2.62029545 -1.35481387 -2.28530167]
E [2.76656933 4.35516499 5.87641465 2.6961484  5.37070206 6.50201751
 1.25748281 8.10011638 6.30513225 1.92482654]


In [33]:
ones((Ntraces)) * parameters.T[0].flatten()

array([-2.98769294,  1.76566497, -3.39611336,  3.47627221, -0.81500201,
       -0.31505363, -0.7537218 , -2.62029545, -1.35481387, -2.28530167])

In [40]:
ones((Ntraces, len(parameters.T[0]))) 

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [56]:
popsize = len(parameters.T[0])
popsize

10

In [57]:
Ntraces

5

In [60]:
x = (ones((Ntraces, popsize)) * parameters.T[0]).T.flatten()
x

array([-2.98769294, -2.98769294, -2.98769294, -2.98769294, -2.98769294,
        1.76566497,  1.76566497,  1.76566497,  1.76566497,  1.76566497,
       -3.39611336, -3.39611336, -3.39611336, -3.39611336, -3.39611336,
        3.47627221,  3.47627221,  3.47627221,  3.47627221,  3.47627221,
       -0.81500201, -0.81500201, -0.81500201, -0.81500201, -0.81500201,
       -0.31505363, -0.31505363, -0.31505363, -0.31505363, -0.31505363,
       -0.7537218 , -0.7537218 , -0.7537218 , -0.7537218 , -0.7537218 ,
       -2.62029545, -2.62029545, -2.62029545, -2.62029545, -2.62029545,
       -1.35481387, -1.35481387, -1.35481387, -1.35481387, -1.35481387,
       -2.28530167, -2.28530167, -2.28530167, -2.28530167, -2.28530167])

In [64]:
x.reshape((popsize,Ntraces))

array([[-2.98769294, -2.98769294, -2.98769294, -2.98769294, -2.98769294],
       [ 1.76566497,  1.76566497,  1.76566497,  1.76566497,  1.76566497],
       [-3.39611336, -3.39611336, -3.39611336, -3.39611336, -3.39611336],
       [ 3.47627221,  3.47627221,  3.47627221,  3.47627221,  3.47627221],
       [-0.81500201, -0.81500201, -0.81500201, -0.81500201, -0.81500201],
       [-0.31505363, -0.31505363, -0.31505363, -0.31505363, -0.31505363],
       [-0.7537218 , -0.7537218 , -0.7537218 , -0.7537218 , -0.7537218 ],
       [-2.62029545, -2.62029545, -2.62029545, -2.62029545, -2.62029545],
       [-1.35481387, -1.35481387, -1.35481387, -1.35481387, -1.35481387],
       [-2.28530167, -2.28530167, -2.28530167, -2.28530167, -2.28530167]])

In [65]:
mean(x.reshape((popsize,Ntraces)), axis=1)

array([-2.98769294,  1.76566497, -3.39611336,  3.47627221, -0.81500201,
       -0.31505363, -0.7537218 , -2.62029545, -1.35481387, -2.28530167])

In [68]:
t = (1.7527717276992988e-08, 8.96082919250482e-05, 0.00013679409495386864)
t

(1.7527717276992988e-08, 8.96082919250482e-05, 0.00013679409495386864)

In [71]:
params_correct = {'gl': float(5e-5),
          'g_na': float(100),
          'g_kd': float(30)}

In [73]:
params = {'gl': t[0],
          'g_na': t[1],
          'g_kd': t[2]}
params

{'gl': 1.7527717276992988e-08,
 'g_na': 8.96082919250482e-05,
 'g_kd': 0.00013679409495386864}

In [75]:
from nevergrad.optimization import optimizerlib
from nevergrad import instrumentation as inst

In [75]:
arg1 = inst.var.Array(1).bounded(200*10e-12, 2*10e-9).asscalar()
arg2 = inst.var.Array(1).bounded(200*10e-9, 40*10e-6).asscalar()
arg3 = inst.var.Array(1).bounded(200*10e-9, 20*10e-6).asscalar()
instrum = inst.Instrumentation(arg1, arg2, arg3)

In [85]:
optim = optimizerlib.registry['DE'](instrumentation=instrum, budget=100000, popsize='large')

TypeError: __call__() got an unexpected keyword argument 'popsize'

In [88]:
from nevergrad.optimization.differentialevolution import DE

In [91]:
DE(instrumentation=instrum, budget=100000, num_workers=2)

Instance of DE(instrumentation=A(1,[At(1.9999999999999997e-09,2e-08)])f,A(1,[At(2e-06,0.0004)])f,A(1,[At(2e-06,0.0002)])f, budget=100000, num_workers=1)

In [84]:
aa = optimizerlib.registry['DE']
aa?


Signature:      
aa(
    instrumentation: Union[int, nevergrad.instrumentation.core.Instrumentation],
    budget: Union[int, NoneType] = None,
    num_workers: int = 1,
) -> nevergrad.optimization.base.Optimizer
Type:            DifferentialEvolution
String form:     DE
File:            ~/anaconda3/envs/brian_opt/lib/python3.7/site-packages/nevergrad/optimization/differentialevolution.py
Docstring:       <no docstring>
Class docstring:
This is a special case of an optimizer family for which the family instance serves to*
hold the parameters.
This class assumes that the attributes are set to the init parameters.
See oneshot.py for examples
Init docstring: 
Differential evolution algorithms.

Default pop size is 30
We return the mean of the individuals with fitness better than median, which might be stupid sometimes.
Default settings are CR =.5, F1=.8, F2=.8, curr-to-best.
Initial population: pure random.

Parameters
----------
initialization: "LHS", "QR" or None
    algorithm for the in