# Dev Notebook for results versions

In [1]:
from brian2 import *

In [2]:
import numpy as np
import pandas as pd

## example data

In [3]:
names = list({'gl', 'g_na', 'g_kd'})
names

['g_na', 'g_kd', 'gl']

In [4]:
type(names)

list

In [5]:
names.append('errors')
names

['g_na', 'g_kd', 'gl', 'errors']

In [6]:
params = [[[6.495285915534006e-05, 0.00030033486708542156, 4.967446676938807e-08], [0.0001331132400694808, 0.00018547890224340113, 1.4860562441875465e-07], [7.199182091336732e-05, 0.00021491256309465835, 1.1198642036996548e-07], [8.923883770663632e-05, 0.00022752133942582876, 7.664424677757521e-08], [0.000123213178985125, 0.0003056879448531054, 1.5616656874380151e-07]], [[0.00011893999263132052, 0.00016377579251686613, 7.62522242482823e-08], [0.00010048677683973367, 0.0003260040956373385, 1.4433294453012082e-07], [5.303782965547715e-05, 0.0001602806339592511, 6.648470240615252e-08], [0.0001269484657797785, 0.0001901034727514455, 1.639848387448191e-07], [0.0001561851135265635, 0.00010512042426624969, 1.593454062525051e-07]]]

In [7]:
params

[[[6.495285915534006e-05, 0.00030033486708542156, 4.967446676938807e-08],
  [0.0001331132400694808, 0.00018547890224340113, 1.4860562441875465e-07],
  [7.199182091336732e-05, 0.00021491256309465835, 1.1198642036996548e-07],
  [8.923883770663632e-05, 0.00022752133942582876, 7.664424677757521e-08],
  [0.000123213178985125, 0.0003056879448531054, 1.5616656874380151e-07]],
 [[0.00011893999263132052, 0.00016377579251686613, 7.62522242482823e-08],
  [0.00010048677683973367, 0.0003260040956373385, 1.4433294453012082e-07],
  [5.303782965547715e-05, 0.0001602806339592511, 6.648470240615252e-08],
  [0.0001269484657797785, 0.0001901034727514455, 1.639848387448191e-07],
  [0.0001561851135265635, 0.00010512042426624969, 1.593454062525051e-07]]]

In [8]:
params = np.array(params)
params

array([[[6.49528592e-05, 3.00334867e-04, 4.96744668e-08],
        [1.33113240e-04, 1.85478902e-04, 1.48605624e-07],
        [7.19918209e-05, 2.14912563e-04, 1.11986420e-07],
        [8.92388377e-05, 2.27521339e-04, 7.66442468e-08],
        [1.23213179e-04, 3.05687945e-04, 1.56166569e-07]],

       [[1.18939993e-04, 1.63775793e-04, 7.62522242e-08],
        [1.00486777e-04, 3.26004096e-04, 1.44332945e-07],
        [5.30378297e-05, 1.60280634e-04, 6.64847024e-08],
        [1.26948466e-04, 1.90103473e-04, 1.63984839e-07],
        [1.56185114e-04, 1.05120424e-04, 1.59345406e-07]]])

In [9]:
np.shape(params)

(2, 5, 3)

In [10]:
params = params.reshape(-1, params.shape[-1])
params

array([[6.49528592e-05, 3.00334867e-04, 4.96744668e-08],
       [1.33113240e-04, 1.85478902e-04, 1.48605624e-07],
       [7.19918209e-05, 2.14912563e-04, 1.11986420e-07],
       [8.92388377e-05, 2.27521339e-04, 7.66442468e-08],
       [1.23213179e-04, 3.05687945e-04, 1.56166569e-07],
       [1.18939993e-04, 1.63775793e-04, 7.62522242e-08],
       [1.00486777e-04, 3.26004096e-04, 1.44332945e-07],
       [5.30378297e-05, 1.60280634e-04, 6.64847024e-08],
       [1.26948466e-04, 1.90103473e-04, 1.63984839e-07],
       [1.56185114e-04, 1.05120424e-04, 1.59345406e-07]])

In [11]:
np.flatten?

Object `np.flatten` not found.


In [12]:
errors =  [array([0.85911275, 0.39971795, 0.39727095, 0.26695162, 0.74139398]), array([0.27571116, 0.80124115, 0.38545814, 0.4795095 , 0.68183738])]

In [13]:
errors = np.array(errors)

In [14]:
errors = np.array([errors.flatten()])
errors

array([[0.85911275, 0.39971795, 0.39727095, 0.26695162, 0.74139398,
        0.27571116, 0.80124115, 0.38545814, 0.4795095 , 0.68183738]])

In [15]:
np.shape(params)

(10, 3)

In [16]:
np.shape(errors)

(1, 10)

## DataFrame option

In [17]:
data = np.concatenate((params, errors.transpose()), axis=1)
data

array([[6.49528592e-05, 3.00334867e-04, 4.96744668e-08, 8.59112750e-01],
       [1.33113240e-04, 1.85478902e-04, 1.48605624e-07, 3.99717950e-01],
       [7.19918209e-05, 2.14912563e-04, 1.11986420e-07, 3.97270950e-01],
       [8.92388377e-05, 2.27521339e-04, 7.66442468e-08, 2.66951620e-01],
       [1.23213179e-04, 3.05687945e-04, 1.56166569e-07, 7.41393980e-01],
       [1.18939993e-04, 1.63775793e-04, 7.62522242e-08, 2.75711160e-01],
       [1.00486777e-04, 3.26004096e-04, 1.44332945e-07, 8.01241150e-01],
       [5.30378297e-05, 1.60280634e-04, 6.64847024e-08, 3.85458140e-01],
       [1.26948466e-04, 1.90103473e-04, 1.63984839e-07, 4.79509500e-01],
       [1.56185114e-04, 1.05120424e-04, 1.59345406e-07, 6.81837380e-01]])

In [18]:
pd.DataFrame(data=data, columns=names)

g_na      g_kd            gl    errors
0  0.000065  0.000300  4.967447e-08  0.859113
1  0.000133  0.000185  1.486056e-07  0.399718
2  0.000072  0.000215  1.119864e-07  0.397271
3  0.000089  0.000228  7.664425e-08  0.266952
4  0.000123  0.000306  1.561666e-07  0.741394
5  0.000119  0.000164  7.625222e-08  0.275711
6  0.000100  0.000326  1.443329e-07  0.801241
7  0.000053  0.000160  6.648470e-08  0.385458
8  0.000127  0.000190  1.639848e-07  0.479509
9  0.000156  0.000105  1.593454e-07  0.681837

## Dict of list

In [19]:
errors

array([[0.85911275, 0.39971795, 0.39727095, 0.26695162, 0.74139398,
        0.27571116, 0.80124115, 0.38545814, 0.4795095 , 0.68183738]])

In [20]:
params

array([[6.49528592e-05, 3.00334867e-04, 4.96744668e-08],
       [1.33113240e-04, 1.85478902e-04, 1.48605624e-07],
       [7.19918209e-05, 2.14912563e-04, 1.11986420e-07],
       [8.92388377e-05, 2.27521339e-04, 7.66442468e-08],
       [1.23213179e-04, 3.05687945e-04, 1.56166569e-07],
       [1.18939993e-04, 1.63775793e-04, 7.62522242e-08],
       [1.00486777e-04, 3.26004096e-04, 1.44332945e-07],
       [5.30378297e-05, 1.60280634e-04, 6.64847024e-08],
       [1.26948466e-04, 1.90103473e-04, 1.63984839e-07],
       [1.56185114e-04, 1.05120424e-04, 1.59345406e-07]])

In [21]:
params[:, 0]

array([6.49528592e-05, 1.33113240e-04, 7.19918209e-05, 8.92388377e-05,
       1.23213179e-04, 1.18939993e-04, 1.00486777e-04, 5.30378297e-05,
       1.26948466e-04, 1.56185114e-04])

In [22]:
arr = params

In [23]:
res_dict = dict()

In [24]:
for i, n in enumerate(names):
    res_dict[n] = data[:, i]

In [25]:
res_dict

{'g_na': array([6.49528592e-05, 1.33113240e-04, 7.19918209e-05, 8.92388377e-05,
        1.23213179e-04, 1.18939993e-04, 1.00486777e-04, 5.30378297e-05,
        1.26948466e-04, 1.56185114e-04]),
 'g_kd': array([0.00030033, 0.00018548, 0.00021491, 0.00022752, 0.00030569,
        0.00016378, 0.000326  , 0.00016028, 0.0001901 , 0.00010512]),
 'gl': array([4.96744668e-08, 1.48605624e-07, 1.11986420e-07, 7.66442468e-08,
        1.56166569e-07, 7.62522242e-08, 1.44332945e-07, 6.64847024e-08,
        1.63984839e-07, 1.59345406e-07]),
 'errors': array([0.85911275, 0.39971795, 0.39727095, 0.26695162, 0.74139398,
        0.27571116, 0.80124115, 0.38545814, 0.4795095 , 0.68183738])}

## List of Dict

In [26]:
len(params)

10

In [27]:
res_list = []

for j in np.arange(0,len(params)):
    temp_data = data[j]
    res_dict = dict()

    for i, n in enumerate(names):
        res_dict[n] = temp_data[i]
    
    res_list.append(res_dict)

In [28]:
res_list

[{'g_na': 6.495285915534006e-05,
  'g_kd': 0.00030033486708542156,
  'gl': 4.967446676938807e-08,
  'errors': 0.85911275},
 {'g_na': 0.0001331132400694808,
  'g_kd': 0.00018547890224340113,
  'gl': 1.4860562441875465e-07,
  'errors': 0.39971795},
 {'g_na': 7.199182091336732e-05,
  'g_kd': 0.00021491256309465835,
  'gl': 1.1198642036996548e-07,
  'errors': 0.39727095},
 {'g_na': 8.923883770663632e-05,
  'g_kd': 0.00022752133942582876,
  'gl': 7.664424677757521e-08,
  'errors': 0.26695162},
 {'g_na': 0.000123213178985125,
  'g_kd': 0.0003056879448531054,
  'gl': 1.5616656874380151e-07,
  'errors': 0.74139398},
 {'g_na': 0.00011893999263132052,
  'g_kd': 0.00016377579251686613,
  'gl': 7.62522242482823e-08,
  'errors': 0.27571116},
 {'g_na': 0.00010048677683973367,
  'g_kd': 0.0003260040956373385,
  'gl': 1.4433294453012082e-07,
  'errors': 0.80124115},
 {'g_na': 5.303782965547715e-05,
  'g_kd': 0.0001602806339592511,
  'gl': 6.648470240615252e-08,
  'errors': 0.38545814},
 {'g_na': 0.000

In [29]:
np.shape(res_list)

(10,)

### short things down

In [30]:
params = [[[6.495285915534006e-05, 0.00030033486708542156, 4.967446676938807e-08], [0.0001331132400694808, 0.00018547890224340113, 1.4860562441875465e-07], [7.199182091336732e-05, 0.00021491256309465835, 1.1198642036996548e-07], [8.923883770663632e-05, 0.00022752133942582876, 7.664424677757521e-08], [0.000123213178985125, 0.0003056879448531054, 1.5616656874380151e-07]], [[0.00011893999263132052, 0.00016377579251686613, 7.62522242482823e-08], [0.00010048677683973367, 0.0003260040956373385, 1.4433294453012082e-07], [5.303782965547715e-05, 0.0001602806339592511, 6.648470240615252e-08], [0.0001269484657797785, 0.0001901034727514455, 1.639848387448191e-07], [0.0001561851135265635, 0.00010512042426624969, 1.593454062525051e-07]]]

In [31]:
params = array(params)
params = params.reshape(-1, params.shape[-1])


In [32]:
names = list({'gl', 'g_na', 'g_kd'}).append('errors')
names

In [33]:
names = list(self.parameter_names)
names.append('errors')

NameError: name 'self' is not defined

In [34]:
errors =  [array([0.85911275, 0.39971795, 0.39727095, 0.26695162, 0.74139398]), array([0.27571116, 0.80124115, 0.38545814, 0.4795095 , 0.68183738])]
errors

[array([0.85911275, 0.39971795, 0.39727095, 0.26695162, 0.74139398]),
 array([0.27571116, 0.80124115, 0.38545814, 0.4795095 , 0.68183738])]

In [35]:
errors = array([array(errors).flatten()])
errors

array([[0.85911275, 0.39971795, 0.39727095, 0.26695162, 0.74139398,
        0.27571116, 0.80124115, 0.38545814, 0.4795095 , 0.68183738]])

In [40]:
from brian2 import *

In [41]:
area = 20000*umetre**2
Cm = 1*ufarad*cm**-2 * area
El = -65*mV
EK = -90*mV
ENa = 50*mV
VT = -63*mV

dt = 0.01*ms

In [42]:
# Model for modelfitting
eqs = Equations(
'''
dv/dt = (gl*(El-v) - g_na*(m*m*m)*h*(v-ENa) - g_kd*(n*n*n*n)*(v-EK) + I)/Cm : volt
dm/dt = 0.32*(mV**-1)*(13.*mV-v+VT)/
    (exp((13.*mV-v+VT)/(4.*mV))-1.)/ms*(1-m)-0.28*(mV**-1)*(v-VT-40.*mV)/
    (exp((v-VT-40.*mV)/(5.*mV))-1.)/ms*m : 1
dn/dt = 0.032*(mV**-1)*(15.*mV-v+VT)/
    (exp((15.*mV-v+VT)/(5.*mV))-1.)/ms*(1.-n)-.5*exp((10.*mV-v+VT)/(40.*mV))/ms*n : 1
dh/dt = 0.128*exp((17.*mV-v+VT)/(18.*mV))/ms*(1.-h)-4./(1+exp((40.*mV-v+VT)/(5.*mV)))/ms*h : 1
g_na : siemens (constant)
g_kd : siemens (constant)
gl   : siemens (constant)
''',
Cm=1*ufarad*cm**-2 * area, El=-65*mV, EK=-90*mV, ENa=50*mV, VT=-63*mV)

In [47]:
Equations.dimensions

In [50]:
from brian2 import Quantity

In [51]:
Quantity?

Init signature: Quantity(arr, dim=None, dtype=None, copy=False, force_quantity=False)
Docstring:     
A number with an associated physical dimension. In most cases, it is not
necessary to create a Quantity object by hand, instead use multiplication
and division of numbers with the constant unit names ``second``,
``kilogram``, etc.

Notes
-----
The `Quantity` class defines arithmetic operations which check for
consistency of dimensions and raise the DimensionMismatchError exception
if they are inconsistent. It also defines default and other representations
for a number for printing purposes.

See the documentation on the Unit class for more details
about the available unit names like mvolt, etc.

*Casting rules*

The rules that define the casting operations for
Quantity object are:

1. Quantity op Quantity = Quantity
   Performs dimension checking if appropriate
2. (Scalar or Array) op Quantity = Quantity
   Assumes that the scalar or array is dimensionless

There is one exception to th