# Dev Metric Tests

In [1]:
import numpy as np
from brian2tools import *

from brian2 import *

WARNING    /home/alteska/anaconda3/envs/brian_opt/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
 [py.warnings]


In [2]:
from numpy.testing import assert_array_less

## MSE

In [3]:
metric = MSEMetric()

In [4]:
out_mse = np.random.rand(2,20)
np.shape(out_mse)

(2, 20)

In [5]:
inp_mse = np.random.rand(10,20)
np.shape(inp_mse)

(10, 20)

In [6]:
metric.calc?

Signature: metric.calc(traces, output, n_traces)
Docstring:
Perform the error calculation across all parameters,
calculate error between each output trace and corresponding
simulation. You can also access metric.features, metric.errors.

Parameters
----------
traces: 2D array
    traces to be evaluated
output: array
    goal traces
n_traces:
    number of input traces

Returns
-------
errors: array
    weigheted/mean error for each set of parameters
File:      ~/Desktop/brian/brian2tools/brian2tools/modelfitting/metric.py
Type:      method


In [7]:
metric.get_features(inp_mse, out_mse, 2)
np.shape(metric.features)

(10,)

In [8]:
metric.get_errors(metric.features, 2)
np.shape(metric.errors)

(5,)

In [9]:
np.shape(metric.calc(inp_mse, out_mse, 2))

(5,)

In [10]:
out_from_inp = np.concatenate([inp_mse, inp_mse])
np.shape(out_from_inp)

(20, 20)

In [132]:
feat = np.random.rand(10,1)
metric.get_errors(feat, 2)
np.shape(metric.errors)

(5,)

In [11]:
metric.calc(out_mse, out_mse, 2)

array([0.])

In [12]:
metric.calc(inp_mse, out_mse, 2)

array([4.49571203, 3.41778225, 3.61762912, 3.30116205, 3.78749377])

In [13]:
np.all((np.greater(metric.calc(inp_mse, out_mse, 2), 0)))

True

In [126]:
metric.get_features(out_mse, out_mse, 2)
np.array(metric.features) > 0

array([False, False])

## Gamma Factor

In [14]:
get_gamma_factor?

Signature: get_gamma_factor(source, target, delta, dt)
Docstring:
Calculate gamma factor between source and tagret spike trains,
with precision delta.

Parameters
----------
source: list/array
    source trace, goal performance
target: list/array
    target trace
delta: float * ms
    time window
dt: float * ms
    time step

Returns
-------
    gamma factor: float
File:      ~/Desktop/brian/brian2tools/brian2tools/modelfitting/metric.py
Type:      function


In [15]:
src = [1, 3, 5, 7, 9, 11] * ms
src

array([ 1.,  3.,  5.,  7.,  9., 11.]) * msecond

In [16]:
src2 = [0, 2, 4, 6, 8] * ms
src2

array([0., 2., 4., 6., 8.]) * msecond

In [17]:
trg = [0, 2, 4, 6, 8] * ms
trg

array([0., 2., 4., 6., 8.]) * msecond

In [18]:
get_gamma_factor(src, trg, 8*ms, 0.1*ms)

0.9090909090909091

In [19]:
get_gamma_factor(src2, trg, 10*ms, 0.1*ms)

1.0

In [20]:
get_gamma_factor([1,2]*ms, [0, 1]*ms, 10*ms, 0.1*ms)


1.0

In [21]:
get_gamma_factor([2, 3, 4]*ms, [1, 2]*ms, 10*ms, 0.1*ms)

0.8

In [22]:
get_gamma_factor([2, 3, 4]*ms, [2,3,4]*ms, 10*ms, 0.1*ms)

1.0

In [23]:
get_gamma_factor([2, 3, 4]*ms, [2,3]*ms, 1*ms, 0.1*ms)

0.8

In [82]:
metric2 = GammaFactor(delta=20*ms, dt=0.01*ms)

In [86]:
# np.random.rand(10, 2) * 10

In [87]:
inp_gf = np.random.normal(loc=10, scale=4, size=(10, 5))
out_gf = np.random.normal(loc=10, scale=4, size=(1, 5))
inp_gf = np.round(np.sort(np.abs(inp_gf)), 2)
out_gf = np.round(np.sort(np.abs(out_gf)), 2)

In [88]:
print(np.round(inp_gf, 2))

[[10.56 10.69 13.46 13.92 20.72]
 [ 4.29  4.5  10.3  11.62 14.73]
 [ 8.72 10.69 12.25 12.99 14.68]
 [ 3.36  4.92  7.54  9.23 11.81]
 [ 5.45  5.52  9.34 14.43 15.55]
 [ 5.59  8.08  8.41 10.15 13.26]
 [ 2.77  8.78  8.88 11.64 13.7 ]
 [ 4.51 10.48 10.5  14.14 16.16]
 [ 7.13  7.88 10.05 12.28 21.97]
 [ 3.01  5.01 10.96 11.54 13.26]]


In [89]:
print(np.round(out_gf, 2))

[[ 4.99  9.15 13.59 14.68 16.41]]


In [90]:
errors = metric2.calc(inp_gf*ms, out_gf*ms, 1)
errors[0]

[2.220446049250313e-16, 2.220446049250313e-16, 2.220446049250313e-16, 2.220446049250313e-16, 2.220446049250313e-16, 2.220446049250313e-16, 2.220446049250313e-16, 2.220446049250313e-16, 2.220446049250313e-16, 2.220446049250313e-16]
[2.22044605e-16 2.22044605e-16 2.22044605e-16 2.22044605e-16
 2.22044605e-16 2.22044605e-16 2.22044605e-16 2.22044605e-16
 2.22044605e-16 2.22044605e-16]


2.220446049250313e-16

In [91]:
errors = metric2.calc(out_gf*ms, out_gf*ms, 1)
errors[0]

[2.220446049250313e-16]
[2.22044605e-16]


2.220446049250313e-16

In [92]:
inp_gf = np.random.rand(10, 5) * 10
out_gf = np.random.rand(1, 5) * 10
inp_gf = np.round(np.sort(inp_gf), 2)
out_gf = np.round(np.sort(out_gf), 2)

In [93]:
print(inp_gf)
print(out_gf)

[[2.18 5.1  5.48 9.23 9.28]
 [0.46 4.63 5.22 8.66 9.84]
 [0.73 0.91 3.63 8.53 8.82]
 [3.47 4.39 8.16 8.64 9.12]
 [3.54 4.09 7.14 9.15 9.99]
 [2.3  3.21 4.64 7.09 9.88]
 [0.62 1.99 3.07 4.45 4.98]
 [1.63 1.87 3.69 8.14 9.84]
 [1.53 2.2  6.11 6.73 7.16]
 [0.02 1.14 1.53 2.84 8.27]]
[[0.57 4.73 8.24 8.9  9.42]]


In [94]:
print(inp_gf)
print(out_gf[0])

[[2.18 5.1  5.48 9.23 9.28]
 [0.46 4.63 5.22 8.66 9.84]
 [0.73 0.91 3.63 8.53 8.82]
 [3.47 4.39 8.16 8.64 9.12]
 [3.54 4.09 7.14 9.15 9.99]
 [2.3  3.21 4.64 7.09 9.88]
 [0.62 1.99 3.07 4.45 4.98]
 [1.63 1.87 3.69 8.14 9.84]
 [1.53 2.2  6.11 6.73 7.16]
 [0.02 1.14 1.53 2.84 8.27]]
[0.57 4.73 8.24 8.9  9.42]


In [95]:
inp_gf*ms

array([[2.18, 5.1 , 5.48, 9.23, 9.28],
       [0.46, 4.63, 5.22, 8.66, 9.84],
       [0.73, 0.91, 3.63, 8.53, 8.82],
       [3.47, 4.39, 8.16, 8.64, 9.12],
       [3.54, 4.09, 7.14, 9.15, 9.99],
       [2.3 , 3.21, 4.64, 7.09, 9.88],
       [0.62, 1.99, 3.07, 4.45, 4.98],
       [1.63, 1.87, 3.69, 8.14, 9.84],
       [1.53, 2.2 , 6.11, 6.73, 7.16],
       [0.02, 1.14, 1.53, 2.84, 8.27]]) * msecond

In [96]:
errors = metric2.calc(inp_gf*ms, out_gf*ms, 1)
errors[0]

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


0.0

In [97]:
metric2.calc(out_gf*ms, out_gf*ms, 1)

[0.0]
[0.]


array([0.])

In [103]:
(inp_gf[0])

out_gf[0]

In [119]:
get_gamma_factor(out_gf[0]*ms, out_gf[0]*ms, delta=20*ms, dt=0.01*ms)

1.0

In [120]:
get_gamma_factor(inp_gf[0]*ms, out_gf[0]*ms, delta=30*ms, dt=0.01*ms)

1.0