# Map Wrapper Development for Scipy Differential Equation

Proof of concept notebook for first Scipy, since it only requires map not the o

Error_function is a pass function.
Our "map" takes care of initiating the whole neuron group, calculating the errors and returing the value.

```
params, fits, error = fit_traces(model = model, input_var = 'v', output_var = 'I',\
                                 input = input_traces, output = output_traces,
                                 dt = 0.1*ms, g = [1*nS, 30*nS], E = [-20*mV,100*mV],
                                 tol = 1e-6)
```

In [1]:
import numpy as np
import multiprocessing as mp

from scipy.optimize import differential_evolution, rosen
from scipy.optimize._differentialevolution import DifferentialEvolutionSolver


In [2]:
from brian2 import *
from brian2.equations.equations import (DIFFERENTIAL_EQUATION, Equations,
                                        SingleEquation, PARAMETER)
from brian2.input import TimedArray
from brian2 import NeuronGroup, StateMonitor, store, restore, run, defaultclock, second, Quantity
from brian2.stateupdaters.base import StateUpdateMethod



#### Artificial Data

In [3]:
params = np.array([
 [ 1.80869973e-08,  2.50218013e-02],
 [ 1.88373085e-08,  9.89559934e-02], 
 [ 1.88373085e-08,  9.89559934e-02], 
])


In [4]:
params2 = np.array([[ 1.12735759e-08,  8.81556360e-02],
 [ 9.04858783e-09,  8.03343489e-02],
 [ 1.60635907e-08,  1.59710651e-03],
 [ 1.66254878e-09,  2.95479385e-02],
 [ 1.80869973e-08,  2.50218013e-02],])

### Input / Output

In [5]:
input_traces = zeros((10,1))*volt
for i in range(1):
    input_traces[1:,i]=i*10*mV

# Create target current traces
output_traces = 10*nS*input_traces

input = input_traces
output = output_traces

### Parameters 

In [6]:
input_var = 'v'
output_var = 'I'

parameter_names = {'g', 'E'}
method = ('linear', 'exponential_euler', 'euler')
t_start = 0*second
popsize, _ = np.shape(params)
dt = 0.1 *ms
defaultclock.dt = dt

### Calculation for inner parameters

In [7]:
Nsteps, Ntraces = input_traces.shape
# N = popsize * len(parameter_names)
N = popsize
duration = Nsteps*dt

In [8]:
N

3

In [9]:
Ntraces

1

### Setup The Model for Optimization

In [10]:
model = Equations('''
I = g*(v-E) : amp
g : siemens (constant)
E : volt (constant)
''')

In [11]:
state_update_code = StateUpdateMethod.apply_stateupdater(model, {}, method=method)

INFO       No numerical integration method specified, using method 'linear' (took 0.01s). [brian2.stateupdaters.base.method_choice]


### Required Model Operations

In [12]:
model_without_diffeq = Equations([eq for eq in model.ordered
                                      if eq.type != DIFFERENTIAL_EQUATION])
    
# Add a parameter for each differential equation
diffeq_params = Equations([SingleEquation(PARAMETER, varname, model.dimensions[varname])
                           for varname in model.diff_eq_names])

# Our new model:
model = model_without_diffeq + diffeq_params

# Replace input variable by TimedArray
input_traces = TimedArray(input, dt = dt)

In [13]:
input_unit = input.dim
model = model + Equations(input_var + '= input_var(t,i % Ntraces) : '+ "% s" % repr(input_unit))

# Add criterion with TimedArray
output_traces = TimedArray(output, dt = dt)
error_unit = output.dim**2
model = model + Equations('total_error : %s' % repr(error_unit))

In [14]:
neurons = NeuronGroup(Ntraces*N, model, method = method)
neurons.namespace['input_var'] = input_traces
neurons.namespace['output_var'] = output_traces
neurons.namespace['t_start'] = t_start
neurons.namespace['Ntraces'] = Ntraces

# Record error
neurons.run_regularly('total_error +=  (' + output_var + '-output_var(t,i % Ntraces))**2 * int(t>=t_start)',
                      when='end')

# Add the code doing the numerical integration
neurons.run_regularly(state_update_code, when='groups')

store()


In [15]:
neurons

NeuronGroup(clock=Clock(dt=100. * usecond, name='defaultclock'), when=start, order=0, name='neurongroup')

### Dev Map Optimization 

### Create the Dictonaries of Parameters

In [16]:
def parameters_dict(params):
    d = dict()
    for name, value in zip(parameter_names, params.T):
        d[name] = value
            
    return d

In [17]:
d = parameters_dict(params)
d

{'g': array([1.80869973e-08, 1.88373085e-08, 1.88373085e-08]),
 'E': array([0.0250218 , 0.09895599, 0.09895599])}

In [18]:
neurons.get_states()

{'N': array(3),
 'i': array([0, 1, 2], dtype=int32),
 't': 0. * second,
 'dt': 100. * usecond,
 't_in_timesteps': array(0),
 'g': array([0., 0., 0.]) * siemens,
 'E': array([0., 0., 0.]) * volt,
 'total_error': array([0., 0., 0.]) * amp2}

In [19]:
restore()
neurons.set_states(d, units=False)
neurons.get_states()

{'N': array(3),
 'i': array([0, 1, 2], dtype=int32),
 't': 0. * second,
 'dt': 100. * usecond,
 't_in_timesteps': array(0),
 'g': array([18.0869973, 18.8373085, 18.8373085]) * nsiemens,
 'E': array([25.0218013, 98.9559934, 98.9559934]) * mvolt,
 'total_error': array([0., 0., 0.]) * amp2}

In [20]:
run(duration, namespace = {})

In [21]:
e = neurons.total_error/int((duration-t_start)/defaultclock.dt)
e = mean(e.reshape((N,Ntraces)),axis=1)
array(e)

array([2.04818928e-19, 3.47473674e-18, 3.47473674e-18])

## All of the above into one hard-coded function

In [22]:
start_scope()

In [23]:
model = Equations('''
I = g*(v-E) : amp
g : siemens (constant)
E : volt (constant)
''')

In [24]:
state_update_code = StateUpdateMethod.apply_stateupdater(model, {}, method=method)

In [25]:
model_without_diffeq = Equations([eq for eq in model.ordered
                                      if eq.type != DIFFERENTIAL_EQUATION])
    
# Add a parameter for each differential equation
diffeq_params = Equations([SingleEquation(PARAMETER, varname, model.dimensions[varname])
                           for varname in model.diff_eq_names])

# Our new model:
model = model_without_diffeq + diffeq_params

# Replace input variable by TimedArray
input_traces = TimedArray(input, dt = dt)

In [26]:
input_unit = input.dim
model = model + Equations(input_var + '= input_var(t,i % Ntraces) : '+ "% s" % repr(input_unit))

# Add criterion with TimedArray
output_traces = TimedArray(output, dt = dt)
error_unit = output.dim**2
model = model + Equations('total_error : %s' % repr(error_unit))

In [37]:
def calc_error(func, params):
    print(params)
    popsize, _ = np.shape(params)
    N = popsize

#     neurons = NeuronGroup(Ntraces*N, model, method = method)
    neurons = NeuronGroup(N, model, method = method)
    neurons.namespace['input_var'] = input_traces
    neurons.namespace['output_var'] = output_traces
    neurons.namespace['t_start'] = t_start
    neurons.namespace['Ntraces'] = Ntraces

    # Record error
    neurons.run_regularly('total_error +=  (' + output_var + '-output_var(t,i % Ntraces))**2 * int(t>=t_start)',
                          when='end')

    # Add the code doing the numerical integration
    neurons.run_regularly(state_update_code, when='groups')

    d = parameters_dict(params)
    neurons.set_states(d, units=False)
    run(duration, namespace = {})

    e = neurons.total_error/int((duration-t_start)/defaultclock.dt)
    e = mean(e.reshape((N,Ntraces)),axis=1)
    
    return array(e)

In [58]:
def error_pass(x):
    print('x', x)
    pass

In [59]:
calc_error(error_pass, params2)

[[1.12735759e-08 8.81556360e-02]
 [9.04858783e-09 8.03343489e-02]
 [1.60635907e-08 1.59710651e-03]
 [1.66254878e-09 2.95479385e-02]
 [1.80869973e-08 2.50218013e-02]]


array([9.87696585e-19, 5.28401654e-19, 6.58192637e-22, 2.41325473e-21,
       2.04818928e-19])

## Try The Same with Differential Evolution from Scipy

In [60]:
start_scope()

In [61]:
model = Equations('''
I = g*(v-E) : amp
g : siemens (constant)
E : volt (constant)
''')

In [62]:
state_update_code = StateUpdateMethod.apply_stateupdater(model, {}, method=method)

In [63]:
model_without_diffeq = Equations([eq for eq in model.ordered
                                      if eq.type != DIFFERENTIAL_EQUATION])
    
# Add a parameter for each differential equation
diffeq_params = Equations([SingleEquation(PARAMETER, varname, model.dimensions[varname])
                           for varname in model.diff_eq_names])

# Our new model:
model = model_without_diffeq + diffeq_params

# Replace input variable by TimedArray
input_traces = TimedArray(input, dt = dt)

In [64]:
input_unit = input.dim
model = model + Equations(input_var + '= input_var(t,i % Ntraces) : '+ "% s" % repr(input_unit))

# Add criterion with TimedArray
output_traces = TimedArray(output, dt = dt)
error_unit = output.dim**2
model = model + Equations('total_error : %s' % repr(error_unit))

In [65]:
bounds = [(1, 30), (-20, 100)]

In [66]:
differential_evolution(error_pass, bounds, updating='deferred', workers=calc_error, maxiter=1)

[[ 16.57982965  -7.40600637]
 [ 25.21027213  88.7411211 ]
 [ 24.36539379  36.27742011]
 [ 11.64744056  29.68152798]
 [ 18.23492342  52.55453932]
 [ 20.93911297  80.3428974 ]
 [  9.47275948  -0.55806989]
 [ 29.73369066  40.70953223]
 [ 23.3569819   85.58504562]
 [ 20.28635088  19.48372407]
 [  1.38290414   2.57856464]
 [  4.44705892  44.06776417]
 [ 26.92615721  58.01988381]
 [  6.96965232   6.570712  ]
 [ 28.30756136  60.3937154 ]
 [ 21.49800574  95.29577171]
 [ 14.668472    71.76181524]
 [ 16.38632382 -19.3438586 ]
 [ 13.68408973 -15.46359869]
 [  5.49237528  15.0145402 ]
 [ 22.98389252  11.9258756 ]
 [ 18.62937996  66.61316497]
 [ 13.45328302  32.49602967]
 [  2.05265169  78.227641  ]
 [  6.16431893  97.30624632]
 [  9.80121835 -11.61127095]
 [ 27.74930672  50.42998294]
 [  3.50294819  75.36879579]
 [  8.54123186  27.86489718]
 [ 11.51732874  22.87799138]]
[[ 1.30544879e+00 -1.47156880e+00]
 [ 4.38218559e+00  1.04576299e+01]
 [ 6.87384510e+00 -5.16052842e-02]
 [ 2.72426534e+01  3.322

TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'