# Dev Metric Tests

In [1]:
import numpy as np
from brian2tools import *

from brian2 import *

WARNING    /home/alteska/anaconda3/envs/brian_opt/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
 [py.warnings]


In [2]:
from numpy.testing import assert_array_less

## MSE

In [3]:
metric = MSEMetric()

In [4]:
out_mse = np.random.rand(2,20)
np.shape(out_mse)

(2, 20)

In [5]:
inp_mse = np.random.rand(10,20)
np.shape(inp_mse)

(10, 20)

In [6]:
metric.calc?

Signature: metric.calc(traces, output, n_traces)
Docstring:
Perform the error calculation across all parameters,
calculate error between each output trace and corresponding
simulation. You can also access metric.features, metric.errors.

Parameters
----------
traces: 2D array
    traces to be evaluated
output: array
    goal traces
n_traces:
    number of input traces

Returns
-------
errors: array
    weigheted/mean error for each set of parameters
File:      ~/Desktop/brian/brian2tools/brian2tools/modelfitting/metric.py
Type:      method


In [7]:
metric.get_features(inp_mse, out_mse, 2)
np.shape(metric.features)

(10,)

In [8]:
metric.get_errors(metric.features, 2)
np.shape(metric.errors)

(5,)

In [9]:
np.shape(metric.calc(inp_mse, out_mse, 2))

(5,)

In [10]:
out_from_inp = np.concatenate([inp_mse, inp_mse])
np.shape(out_from_inp)

(20, 20)

In [11]:
feat = np.random.rand(10,1)
metric.get_errors(feat, 2)
np.shape(metric.errors)

(5,)

In [12]:
metric.calc(out_mse, out_mse, 2)

array([0.])

In [13]:
metric.calc(inp_mse, out_mse, 2)

array([3.09542491, 2.92969272, 2.78028551, 2.90101725, 3.04136841])

In [14]:
np.all((np.greater(metric.calc(inp_mse, out_mse, 2), 0)))

True

In [15]:
metric.get_features(out_mse, out_mse, 2)
np.array(metric.features) > 0

array([False, False])

## Gamma Factor

In [16]:
get_gamma_factor?

Signature: get_gamma_factor(source, target, delta, dt)
Docstring:
Calculate gamma factor between source and tagret spike trains,
with precision delta.

Parameters
----------
source: list/array
    source trace, goal performance
target: list/array
    target trace
delta: float * ms
    time window
dt: float * ms
    time step

Returns
-------
    gamma factor: float
File:      ~/Desktop/brian/brian2tools/brian2tools/modelfitting/metric.py
Type:      function


In [17]:
src = [1, 3, 5, 7, 9, 11] * ms
src

array([ 1.,  3.,  5.,  7.,  9., 11.]) * msecond

In [18]:
src2 = [0, 2, 4, 6, 8] * ms
src2

array([0., 2., 4., 6., 8.]) * msecond

In [19]:
trg = [0, 2, 4, 6, 8] * ms
trg

array([0., 2., 4., 6., 8.]) * msecond

In [20]:
get_gamma_factor(src, trg, 8*ms, 0.1*ms)

0.9090909090909091

In [21]:
get_gamma_factor(src2, trg, 10*ms, 0.1*ms)

1.0

In [22]:
get_gamma_factor([1,2]*ms, [0, 1]*ms, 10*ms, 0.1*ms)


1.0

In [23]:
get_gamma_factor([2, 3, 4]*ms, [1, 2]*ms, 10*ms, 0.1*ms)

0.8

In [24]:
get_gamma_factor([2, 3, 4]*ms, [2,3,4]*ms, 10*ms, 0.1*ms)

1.0

In [25]:
get_gamma_factor([2, 3, 4]*ms, [2,3]*ms, 1*ms, 0.1*ms)

0.8

In [26]:
metric2 = GammaFactor(delta=20*ms, dt=0.01*ms)

In [68]:
# two different traces
src = [1, 3, 5, 7, 9, 11] * ms
src2 = [0, 2, 4, 6, 8] * ms
trg = [0, 2, 4, 6, 8] * ms

print(get_gamma_factor(src, trg, delta=122*ms, dt=0.1*ms))
print(get_gamma_factor(src2, trg, delta=10*ms, dt=0.1*ms))

0.9090909090909091
1.0


In [73]:
# two different traces
src = [7, 9, 11] * ms
src2 = [1, 2, 3] * ms
trg = [0, 2, 4, 6, 8] * ms

print(get_gamma_factor(trg, trg, delta=12*ms, dt=0.1*ms))
print(get_gamma_factor(src2, trg, delta=12*ms, dt=0.1*ms))
print(get_gamma_factor(src, src2, delta=5*ms, dt=0.1*ms))

1.0
1.25
1.037037037037037


In [74]:
# np.random.rand(10, 2) * 10

In [28]:
inp_gf = np.random.normal(loc=10, scale=4, size=(10, 5))
out_gf = np.random.normal(loc=10, scale=4, size=(1, 5))
inp_gf = np.round(np.sort(np.abs(inp_gf)), 2)
out_gf = np.round(np.sort(np.abs(out_gf)), 2)

In [29]:
print(np.round(inp_gf, 2))

[[ 0.95  3.6  11.47 13.6  13.96]
 [ 4.39  5.46  6.88  7.68 11.15]
 [ 8.34  8.96  9.34 12.04 12.56]
 [ 5.04  7.51  8.14  8.57 14.72]
 [ 5.86  7.25 10.43 12.4  12.5 ]
 [ 5.91  8.62  9.29 15.62 21.46]
 [ 8.51  8.53  9.9  12.16 18.06]
 [ 9.89 10.13 11.7  14.27 15.05]
 [ 1.43  7.39 10.29 11.39 12.53]
 [ 4.97  6.63  9.48 10.96 12.  ]]


In [30]:
print(np.round(out_gf, 2))

[[ 7.64  9.76 11.68 11.84 15.4 ]]


In [31]:
errors = metric2.calc(inp_gf*ms, out_gf*ms, 1)
np.shape(errors)


(10,)

In [32]:
errors = metric2.calc(out_gf*ms, out_gf*ms, 1)
errors[0]

0.0

In [33]:
inp_gf = np.random.rand(10, 5) * 10
out_gf = np.random.rand(1, 5) * 10
inp_gf = np.round(np.sort(inp_gf), 2)
out_gf = np.round(np.sort(out_gf), 2)

In [34]:
print(inp_gf)
print(out_gf)

[[1.05 2.69 3.28 7.76 8.15]
 [0.29 3.81 4.87 6.74 7.91]
 [2.39 5.85 6.15 7.89 7.97]
 [0.1  1.74 4.24 9.12 9.45]
 [2.63 4.02 6.1  8.32 9.67]
 [2.29 2.57 4.11 4.86 7.44]
 [1.86 3.82 3.99 6.51 9.32]
 [0.29 5.72 8.24 9.12 9.52]
 [0.69 2.46 4.87 6.44 8.56]
 [3.22 3.67 5.49 8.37 8.93]]
[[1.55 4.3  6.04 7.14 8.08]]


In [35]:
print(inp_gf[0])
print(out_gf[0])

[1.05 2.69 3.28 7.76 8.15]
[1.55 4.3  6.04 7.14 8.08]


In [36]:
inp_gf*ms

array([[1.05, 2.69, 3.28, 7.76, 8.15],
       [0.29, 3.81, 4.87, 6.74, 7.91],
       [2.39, 5.85, 6.15, 7.89, 7.97],
       [0.1 , 1.74, 4.24, 9.12, 9.45],
       [2.63, 4.02, 6.1 , 8.32, 9.67],
       [2.29, 2.57, 4.11, 4.86, 7.44],
       [1.86, 3.82, 3.99, 6.51, 9.32],
       [0.29, 5.72, 8.24, 9.12, 9.52],
       [0.69, 2.46, 4.87, 6.44, 8.56],
       [3.22, 3.67, 5.49, 8.37, 8.93]]) * msecond

In [37]:
errors = metric2.calc(inp_gf*ms, out_gf*ms, 1)
errors[0]

2.220446049250313e-16

In [38]:
metric2.calc(out_gf*ms, out_gf*ms, 1)

array([2.22044605e-16])

In [39]:
(inp_gf[0])
out_gf[0]

array([1.55, 4.3 , 6.04, 7.14, 8.08])

In [40]:
get_gamma_factor(out_gf[0]*ms, out_gf[0]*ms, delta=20*ms, dt=0.01*ms)

1.0000000000000002

In [41]:
get_gamma_factor(inp_gf[0]*ms, out_gf[0]*ms, delta=6*ms, dt=0.01*ms)

0.9999999999999999

In [42]:
inp_gf[0]*ms

array([1.05, 2.69, 3.28, 7.76, 8.15]) * msecond

In [43]:
out_gf[0]*ms

array([1.55, 4.3 , 6.04, 7.14, 8.08]) * msecond

In [44]:
from numpy.testing.utils import assert_equal, assert_raises, assert_array_less

mse = MSEMetric()
out = np.random.rand(2, 20)
inp = np.random.rand(10, 20)

errors = mse.calc(inp, out, 2)
assert_equal(np.shape(errors), (5,))
assert_equal(mse.calc(out, out, 2), [0.])
assert(np.all(mse.calc(inp, out, 2) > 0))

In [49]:
# calc GammaFactor
assert_raises(TypeError, GammaFactor)
assert_raises(TypeError, GammaFactor, delta=10*ms)
assert_raises(AssertionError, GammaFactor, dt=0.01*ms)
assert_raises(DimensionMismatchError, GammaFactor, delta=10*ms, dt=0.01)
assert_raises(DimensionMismatchError, GammaFactor, delta=10, dt=0.01*ms)


In [61]:
inp_gf = np.random.rand(10, 5) * 10
out_gf = np.random.rand(2, 5) * 10
inp_gf = np.round(np.sort(inp_gf), 2)
out_gf = np.round(np.sort(out_gf), 2)

In [62]:
gf = GammaFactor(delta=10*ms, dt=1*ms)
errors = gf.calc(inp_gf, out_gf, 2)

assert_equal(np.shape(errors), (5,))

In [63]:
errors

array([1.01123854, 1.01123854, 1.01123854, 1.01123854, 1.01123854])

In [64]:
errors = gf.calc(out_gf, out_gf, 2)
errors

array([0.])

### Firing Rate

In [76]:
x = [1,2,3]
firing_rate(x)

1.0

In [77]:
x = [1.1, 1.2, 1.3, 1.4, 1.5]
firing_rate(x)

10.000000000000002

In [78]:
x = [1, 1.2, 1.4, 1.6, 1.8]
firing_rate(x)

5.0