In [1]:
from scipy.optimize import differential_evolution
import numpy as np

In [9]:
def ackley(x):
    arg1 = -0.2 * np.sqrt(0.5 * (x[0] ** 2 + x[1] ** 2))
    arg2 = 0.5 * (np.cos(2. * np.pi * x[0]) + np.cos(2. * np.pi * x[1]))
    return -20. * np.exp(arg1) - np.exp(arg2) + 20. + np.e

In [10]:
bounds = [(-5, 5), (-5, 5)]
result = differential_evolution(ackley, bounds)
result.x, result.fun

(array([0., 0.]), 4.440892098500626e-16)

In [11]:
result = differential_evolution(ackley, bounds, workers=2)
result.x, result.fun

(array([0., 0.]), 4.440892098500626e-16)

In [14]:
from multiprocessing import Pool

In [23]:
mm = Pool(processes=2)

In [25]:
def multi_run_wrapper(args):
    return add(*args)
def add(x,y):
    return x+y

In [26]:
pool = Pool(4)
results = pool.map(multi_run_wrapper,[(1,2),(2,3),(3,4)])
results

[3, 5, 7]

In [29]:
# result = differential_evolution(ackley, bounds, workers=pool)
# result.x, result.fun

In [30]:
test_vec = np.array([1,2,3])

def test_f (x):
    return x+2

In [48]:
x0 = np.array(0)
x0.


array(0)

In [56]:
def square(x):
    x0 = []
    for d in x:
        print(d)
        x0.append(np.sum((d - .5)**2))
    return np.array(x0)

In [57]:
square(test_vec)

1
2
3


array([0.25, 2.25, 6.25])

In [63]:
# result = differential_evolution(square, bounds, workers=pool.map(test_f,test_vec))
# result = differential_evolution(square, bounds, workers=pool.map(square,test_vec))

In [ ]:
pool = Pool(6)
results = pool.map(square, test_vec)

In [ ]:
# result = differential_evolution(ackley, bounds, workers=1)
result = differential_evolution(ackley, bounds, workers=pool.map(test_f,test_vec))


In [64]:
import multiprocessing as mp

In [65]:
def cube(x):
    return x**3

In [74]:
pool = mp.Pool(processes=2)
results = pool.map(cube, range(1,2))
print(results)

[1]


In [80]:
differential_evolution(cube, [(-5, 5)], workers=2)

     fun: array([-125.])
     jac: array([74.99999981])
 message: 'Optimization terminated successfully.'
    nfev: 214
     nit: 13
 success: True
       x: array([-5.])

In [89]:
map(lambda x: cube(x), range(1,3))

In [102]:
pool = Pool(4)
worker = pool.map(cube, range(1,3))
pool.map(cube, range(1,3))

[1, 8]

In [116]:
class MapTest():
        
    def map(self, func, iterable):
        return map(func, iterable)

In [126]:
callable(MapTest.map)

True

In [112]:
class MapWrapper(object):
    """
    Parallelisation wrapper for working with map-like callables, such as
    `multiprocessing.Pool.map`.

    Parameters
    ----------
    pool : int or map-like callable
        If `pool` is an integer, then it specifies the number of threads to
        use for parallelization. If ``int(pool) == 1``, then no parallel
        processing is used and the map builtin is used.
        If ``pool == -1``, then the pool will utilise all available CPUs.
        If `pool` is a map-like callable that follows the same
        calling sequence as the built-in map function, then this callable is
        used for parallelisation.
    """
    def __init__(self, pool=1):
        self.pool = None
        self._mapfunc = map
        self._own_pool = False
        print(callable(pool))
        if callable(pool):
            self.pool = pool
            self._mapfunc = self.pool
        else:
            # user supplies a number
            if int(pool) == -1:
                # use as many processors as possible
                self.pool = Pool()
                self._mapfunc = self.pool.map
                self._own_pool = True
            elif int(pool) == 1:
                pass
            elif int(pool) > 1:
                # use the number of processors requested
                self.pool = Pool(processes=int(pool))
                self._mapfunc = self.pool.map
                self._own_pool = True
            else:
                raise RuntimeError("Number of workers specified must be -1,"
                                   " an int >= 1, or an object with a 'map' method")


In [121]:
MapWrapper(pool=MapTest)

True


In [131]:
# differential_evolution(cube, [(-5, 5), (-2,10) ], workers=MapTest.map)
differential_evolution(cube, [(-5, 5) ], workers=map)


     fun: -124.99953845622126
 message: 'Optimization terminated successfully.'
    nfev: 167
     nit: 10
 success: True
       x: array([-4.99999385])

In [ ]:
# result = differential_evolution(ackley, bounds, workers=pool)
# result.x, result.fun