# Test SkOpt with ask () tell() and Neuron Group

### Example from their git

In [1]:
import numpy as np

from brian2 import *
from brian2.equations.equations import (DIFFERENTIAL_EQUATION, Equations,
                                        SingleEquation, PARAMETER)
from brian2.input import TimedArray
from brian2 import NeuronGroup, StateMonitor, store, restore, run, defaultclock, second, Quantity
from brian2.stateupdaters.base import StateUpdateMethod



In [2]:
from skopt import Optimizer
from skopt.space import Real
from sklearn.externals.joblib import Parallel, delayed
# example objective taken from skopt
from skopt.benchmarks import branin

WARNING    /home/alteska/anaconda3/envs/brian_opt/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
 [py.warnings]


In [3]:
optimizer = Optimizer(
    dimensions=[Real(-5.0, 10.0), Real(0.0, 15.0)],
    random_state=1,
    base_estimator='gp'
)

In [4]:
for i in range(10): 
    x = optimizer.ask(n_points=4)  # x is a list of n_points points    
    y = Parallel(n_jobs=4)(delayed(branin)(v) for v in x)  # evaluate points in parallel
    print('x', x)
    print('x shape', np.shape(x))
    print('y', y)
    print('y shape', np.shape(y))
    optimizer.tell(x, y)

x [[5.539674886665384, 0.9247759772133487], [0.6533781426078518, 2.1846509309627606], [2.3976321059971877, 13.33388107457551], [-4.122692211373234, 3.835422267410678]]
x shape (4, 2)
y [17.117802423039286, 25.636791759237006, 111.24456644018927, 123.94463659127379]
y shape (4,)
x [[5.253361598114372, 5.019098178016241], [-4.558830399495135, 6.521625092942932], [1.0517974825501595, 11.196568270857433], [-4.341063750925826, 5.52471184343409]]
x shape (4, 2)
y [29.49805986824328, 97.24532144298679, 60.023920779206286, 102.92404054178502]
y shape (4,)
x [[7.455985183109318, 0.20173575763695223], [6.5480183384544315, 4.201808432696337], [6.411163292726274, 1.3168776477532418], [6.035820747326337, 0.0]]
x shape (4, 2)
y [14.96091221397041, 28.78036409352106, 19.567975952807018, 20.519902503043827]
y shape (4,)
x [[7.543548690076646, 0.0], [7.500941007924283, 0.11291580948130737], [3.1589029519796927, 1.551323999490736], [4.536178973049552, 1.4339139689522926]]
x shape (4, 2)
y [14.7430796249

In [5]:
# takes ~ 20 sec to get here
print(min(optimizer.yi))  # print the best objective found

0.3982524854050702


### Same with Separate loops

In [6]:
optimizer = Optimizer(
    dimensions=[Real(-5.0, 10.0), Real(0.0, 15.0)],
    random_state=1,
    base_estimator='gp'
)

In [7]:
n_samples = 1
params = []
candidates = []

for _ in range(n_samples):
    x = optimizer.ask(n_points=10)  # x is a list of n_points points    
    candidates.append(x)


In [8]:
candidates

[[[5.539674886665384, 0.9247759772133487],
  [0.6533781426078518, 2.1846509309627606],
  [2.3976321059971877, 13.33388107457551],
  [-4.122692211373234, 3.835422267410678],
  [2.18434866398996, 10.14131246631503],
  [-0.26536359546881716, 14.474360413114516],
  [-4.635512700781785, 14.054611867944384],
  [7.44081018418634, 2.016921234869212],
  [4.852135388499796, 9.287165289493949],
  [8.747572428177428, 7.5085739238532625]]]

In [9]:
for cand in candidates:
    y = Parallel(n_jobs=1)(delayed(branin)(v) for v in x)  # evaluate points in parallel
    optimizer.tell(cand, y)        
    print(y)

[17.117802423039286, 25.636791759237006, 111.24456644018927, 123.94463659127379, 53.491263803604525, 83.95464222088268, 13.66814170756434, 14.355184112861938, 74.82906435343783, 33.27012035987897]


In [10]:
print(min(optimizer.yi))

13.66814170756434


## Load the Model

### Input

In [11]:
input_traces = zeros((10,1))*volt
for i in range(1):
    input_traces[1:,i]=i*10*mV

In [12]:
# Create target current traces
output_traces = 10*nS*input_traces

In [13]:
input = input_traces
output = output_traces

### Parameters 

In [14]:
params = np.array([
 [ 1.80869973e-08,  2.50218013e-02],
 [ 1.88373085e-08,  9.89559934e-02], 
 [ 1.88373085e-08,  9.89559934e-02], 
])

In [15]:
input_var = 'v'
output_var = 'I'

parameter_names = {'g', 'E'}
method = ('linear', 'exponential_euler', 'euler')
t_start = 0*second
popsize, _ = np.shape(params)
dt = 0.1 *ms
defaultclock.dt = dt

In [16]:
def parameters_dict(params):
    d = dict()
    for name, value in zip(parameter_names, params.T):
        d[name] = value
            
    return d

In [17]:
parameters_dict(params)

{'E': array([1.80869973e-08, 1.88373085e-08, 1.88373085e-08]),
 'g': array([0.0250218 , 0.09895599, 0.09895599])}

### Setup The Model for Optimization

In [18]:
model = Equations('''
I = g*(v-E) : amp
g : siemens (constant)
E : volt (constant)
''')

In [19]:
state_update_code = StateUpdateMethod.apply_stateupdater(model, {}, method=method)

INFO       No numerical integration method specified, using method 'linear' (took 0.00s). [brian2.stateupdaters.base.method_choice]


### Required Model Operations

In [20]:
Nsteps, Ntraces = input_traces.shape
# N = popsize * len(parameter_names)
N = popsize
duration = Nsteps*dt

In [21]:
model_without_diffeq = Equations([eq for eq in model.ordered
                                      if eq.type != DIFFERENTIAL_EQUATION])
    
# Add a parameter for each differential equation
diffeq_params = Equations([SingleEquation(PARAMETER, varname, model.dimensions[varname])
                           for varname in model.diff_eq_names])

# Our new model:
model = model_without_diffeq + diffeq_params

# Replace input variable by TimedArray
input_traces = TimedArray(input, dt = dt)

In [22]:
input_unit = input.dim
model = model + Equations(input_var + '= input_var(t,i % Ntraces) : '+ "% s" % repr(input_unit))

# Add criterion with TimedArray
output_traces = TimedArray(output, dt = dt)
error_unit = output.dim**2
model = model + Equations('total_error : %s' % repr(error_unit))

In [23]:
neurons = NeuronGroup(Ntraces*N, model, method = method)
neurons.namespace['input_var'] = input_traces
neurons.namespace['output_var'] = output_traces
neurons.namespace['t_start'] = t_start
neurons.namespace['Ntraces'] = Ntraces

#### Record error  
additional differential equation calculating the error

In [24]:
neurons.run_regularly('total_error +=  (' + output_var + '-output_var(t,i % Ntraces))**2 * int(t>=t_start)',
                      when='end')

# Add the code doing the numerical integration
neurons.run_regularly(state_update_code, when='groups')

# store the state of the network
store()

In [25]:
def calc_error(params):
    print(params)
    popsize, _ = np.shape(params)
    N = popsize

#     neurons = NeuronGroup(Ntraces*N, model, method = method)
    neurons = NeuronGroup(N, model, method = method)
    neurons.namespace['input_var'] = input_traces
    neurons.namespace['output_var'] = output_traces
    neurons.namespace['t_start'] = t_start
    neurons.namespace['Ntraces'] = Ntraces

    # Record error
    neurons.run_regularly('total_error +=  (' + output_var + '-output_var(t,i % Ntraces))**2 * int(t>=t_start)',
                          when='end')

    # Add the code doing the numerical integration
    neurons.run_regularly(state_update_code, when='groups')

    d = parameters_dict(params)
    neurons.set_states(d, units=False)
    run(duration, namespace = {})

    e = neurons.total_error/int((duration-t_start)/defaultclock.dt)
    e = mean(e.reshape((N,Ntraces)),axis=1)
    
    return array(e)

In [26]:
neurons

NeuronGroup(clock=Clock(dt=100. * usecond, name='defaultclock'), when=start, order=0, name='neurongroup')

### Ask and Tel with calc_error Function

In [27]:
start_scope()

In [28]:
model = Equations('''
I = g*(v-E) : amp
g : siemens (constant)
E : volt (constant)
''')

In [29]:
state_update_code = StateUpdateMethod.apply_stateupdater(model, {}, method=method)

In [30]:
model_without_diffeq = Equations([eq for eq in model.ordered
                                      if eq.type != DIFFERENTIAL_EQUATION])
    
# Add a parameter for each differential equation
diffeq_params = Equations([SingleEquation(PARAMETER, varname, model.dimensions[varname])
                           for varname in model.diff_eq_names])

# Our new model:
model = model_without_diffeq + diffeq_params

# Replace input variable by TimedArray
input_traces = TimedArray(input, dt = dt)

In [31]:
input_unit = input.dim
model = model + Equations(input_var + '= input_var(t,i % Ntraces) : '+ "% s" % repr(input_unit))

# Add criterion with TimedArray
output_traces = TimedArray(output, dt = dt)
error_unit = output.dim**2
model = model + Equations('total_error : %s' % repr(error_unit))

### Ask and Tel with calc_error Function

In [52]:
optimizer = Optimizer(
    dimensions=[Real(-5.0, 5.0), Real(0.0, 10.0)],
    random_state=1,
    base_estimator='gp',
    n_initial_points=100
)

n_samples = 10
params = []
candidates = []

for _ in range(n_samples):
    
    cand = optim.ask()
    candidates.append(cand)
    params.append(list(cand.args))
    
params

In [65]:
n_rounds = 3
n_samples = 10
params = []
candidates = []

In [66]:
for _ in range(n_rounds):
    x = optimizer.ask(n_points=n_samples)  # x is a list of n_points points    
    candidates.append(x)

In [67]:
candidates

[[[1.8355743987429154, 3.3460654520108273],
  [-4.705886932996757, 4.347750061961955],
  [-0.9654683449665598, 7.464378847238288],
  [-4.560709167283884, 3.68314122895606],
  [3.5744788612079574, 9.4723312701606],
  [3.6488626797046955, 3.709716775920511],
  [-3.763924065151137, 4.351649030619424],
  [-3.0902347352929245, 7.058895060453291],
  [-4.6479406539867, 2.0690136289980137],
  [-3.689308009781511, 5.393291730683321]],
 [[1.8355743987429154, 3.3460654520108273],
  [-4.705886932996757, 4.347750061961955],
  [-0.9654683449665598, 7.464378847238288],
  [-4.560709167283884, 3.68314122895606],
  [3.5744788612079574, 9.4723312701606],
  [3.6488626797046955, 3.709716775920511],
  [-3.763924065151137, 4.351649030619424],
  [-3.0902347352929245, 7.058895060453291],
  [-4.6479406539867, 2.0690136289980137],
  [-3.689308009781511, 5.393291730683321]],
 [[1.8355743987429154, 3.3460654520108273],
  [-4.705886932996757, 4.347750061961955],
  [-0.9654683449665598, 7.464378847238288],
  [-4.560

In [68]:
y = []

for n in range(n_rounds):
    y.append(calc_error(np.array(candidates[n])))

[[ 1.8355744   3.34606545]
 [-4.70588693  4.34775006]
 [-0.96546834  7.46437885]
 [-4.56070917  3.68314123]
 [ 3.57447886  9.47233127]
 [ 3.64886268  3.70971678]
 [-3.76392407  4.35164903]
 [-3.09023474  7.05889506]
 [-4.64794065  2.06901363]
 [-3.68930801  5.39329173]]
[[ 1.8355744   3.34606545]
 [-4.70588693  4.34775006]
 [-0.96546834  7.46437885]
 [-4.56070917  3.68314123]
 [ 3.57447886  9.47233127]
 [ 3.64886268  3.70971678]
 [-3.76392407  4.35164903]
 [-3.09023474  7.05889506]
 [-4.64794065  2.06901363]
 [-3.68930801  5.39329173]]
[[ 1.8355744   3.34606545]
 [-4.70588693  4.34775006]
 [-0.96546834  7.46437885]
 [-4.56070917  3.68314123]
 [ 3.57447886  9.47233127]
 [ 3.64886268  3.70971678]
 [-3.76392407  4.35164903]
 [-3.09023474  7.05889506]
 [-4.64794065  2.06901363]
 [-3.68930801  5.39329173]]


In [69]:
y[0]

array([  37.72357536,  418.61242677,   51.93539333,  282.16393363,
       1146.40803704,  183.22998544,  268.28069897,  475.83500822,
         92.48000646,  395.91107855])

In [70]:
for n in range(n_rounds):
    optimizer.tell(candidates[n], y[n].tolist());

In [71]:
min(optimizer.yi)  # print the best objective found    

0.3680235886120897

In [72]:
xi = optimizer.Xi

In [73]:
yii = np.array(optimizer.yi)
yii.argmin()

2

In [74]:
xi[yii.argmin()]

[-0.06824526266854125, 8.889254049717007]